# Generated by Django 3.2.12 on 2022-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_tumor', '0014_remove_user_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylish_details',
            name='Address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Contact',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Email',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Password',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Speciality',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Status',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='stylish_details',
            name='Username',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
