# Generated by Django 4.2.10 on 2024-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_tumor', '0015_auto_20220208_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat_details',
        ),
        migrations.DeleteModel(
            name='Stylish_details',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='ChatStatus',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='City',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='CreditCard',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Cvv',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Expiry',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='ExpiryDate',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='LastName',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='State',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user_details',
            name='Age',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Contact',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Image1',
            field=models.ImageField(default=None, upload_to='img/images'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Symptoms',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Treatment',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Email',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Username',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterModelTable(
            name='user_details',
            table='User_Details',
        ),
    ]
