# Generated by Django 3.2.12 on 2024-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_tumor', '0016_delete_chat_details_delete_stylish_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Class_detected',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
